### ISSUE TITLE
Lodge map is broken on production website

### ISSUE THREAD

**Issue by justdave** [oabsa/lodge-map#3]
Loading the lodge locator map results in a message "This page can't load Google Maps correctly"

and indeed, the search doesn't work.

<img width="1236" alt="Screen Shot 2019-11-13 at 4 55 21 AM" src="https://user-images.githubusercontent.com/307334/68752784-e5cde080-05d1-11ea-9795-6e8441f85eff.png">

**Comment by adamgross42** [comment]
This has been fixed.

@justdave , reopen if you're still seeing this.

**Comment by justdave** [comment]
Confirmed, thanks!
